services:
  - type: web
    name: vibefinderai-backend
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && prisma py fetch && prisma generate
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PRISMA_CACHE_DIR
        value: .prisma
